import { useCallback, useEffect, useRef, useState } from 'react';
import { Orbit, Plus, Play, Pause, RotateCcw, ImageDown, FolderOpen, Download, ChevronLeft, ChevronRight, Copy, Trash2, Sun, SlidersHorizontal, PanelsTopLeft, Upload, Check, X, Maximize2 } from 'lucide-react';
import { Scene, type SceneHandle } from './Scene';
import { Button, ColorField, Field, Slider } from './ui';
import { defaults, download, kinds, kindNames, newCard, newProject, parseProject, type Card, type CardKind, type Project, type Settings } from './model';
import { loadProject, readImage, saveProject } from './storage';
import { paintCard } from './charts';

function Thumbnail({card,large=false}:{card:Card;large?:boolean}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{let canceled=false;const paint=()=>{if(!canceled&&ref.current)paintCard(ref.current,card,1.8);};paint();let id=0;if(card.image){const img=new Image();img.src=card.image;img.decode().then(()=>{id=window.setTimeout(paint,100);}).catch(()=>{});}return()=>{canceled=true;clearTimeout(id);};},[card]);return <canvas ref={ref} width={large?720:240} height={large?480:160} className={large?'card-large':'card-thumb'} aria-label={`${card.title}预览`}/>;}
function ValuesField({values,onChange}:{values:number[];onChange(v:number[]):void}){const [text,setText]=useState(values.join(', '));const [error,setError]=useState('');useEffect(()=>setText(values.join(', ')),[values]);function commit(v:string){setText(v);const parts=v.split(/[,，\s]+/).filter(Boolean);const nums=parts.map(Number);if(!nums.length||nums.length>12||nums.some(n=>!Number.isFinite(n)||n<0||n>100)){setError('输入 1–12 个 0–100 的数值，以逗号分隔。');return;}setError('');onChange(nums);}return <label className="field"><span>图表数值</span><input value={text} onChange={e=>commit(e.target.value)} aria-invalid={!!error} aria-describedby="series-help"/><small id="series-help" className={error?'text-error':''}>{error||'用逗号分隔，范围 0–100。不同图表取对应数量。'}</small></label>;}

export default function App(){
 const [project,setProject]=useState<Project>(()=>newProject());const [selected,setSelected]=useState('');const [tab,setTab]=useState<'scene'|'light'|'card'>('scene');const [playing,setPlaying]=useState(!matchMedia('(prefers-reduced-motion: reduce)').matches);const [seek,setSeek]=useState(0);const [displayTime,setDisplayTime]=useState(0);const [loaded,setLoaded]=useState(false);const [saveState,setSaveState]=useState('正在读取项目');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [undo,setUndo]=useState<Project|null>(null);
 const scene=useRef<SceneHandle>(null),importRef=useRef<HTMLInputElement>(null),imageRef=useRef<HTMLInputElement>(null),studioRef=useRef<HTMLDivElement>(null);const restoreDone=useRef(false);
 useEffect(()=>{let canceled=false;loadProject().then(raw=>{if(canceled)return;if(raw){const p=parseProject(raw);setProject(p);setSelected(p.cards[0]?.id??'');}setSaveState(raw?'已恢复上次项目':'新项目');}).catch(()=>{if(!canceled){setMessage('未能恢复本机项目，已载入默认卡片。');setSaveState('请手动保存项目');}}).finally(()=>{if(!canceled){restoreDone.current=true;setLoaded(true);}});return()=>{canceled=true;};},[]);
 useEffect(()=>{if(!restoreDone.current)return;setSaveState('正在保存…');const t=setTimeout(()=>{saveProject(project).then(()=>setSaveState('已自动保存')).catch(()=>setSaveState('自动保存失败，请下载项目'));},600);return()=>clearTimeout(t);},[project,loaded]);
 useEffect(()=>{if(!selected&&project.cards.length)setSelected(project.cards[0].id);},[project.cards,selected]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),6500);return()=>clearTimeout(t);},[message]);
 const changeSetting=useCallback(<K extends keyof Settings,>(k:K,v:Settings[K])=>setProject(p=>({...p,settings:{...p.settings,[k]:v}})),[]);
 const onDrag=useCallback((pitch:number,yaw:number)=>setProject(p=>({...p,settings:{...p.settings,pitch,yaw}})),[]);
 const active=project.cards.find(c=>c.id===selected);const settings=project.settings;
 function patchCard(patch:Partial<Card>){setProject(p=>({...p,cards:p.cards.map(c=>c.id===selected?{...c,...patch}:c)}));}
 function add(){if(project.cards.length>=16)return;const c=newCard('bar');setProject(p=>({...p,cards:[...p.cards,c]}));setSelected(c.id);setTab('card');}
 function duplicate(){if(!active||project.cards.length>=16)return;const c={...active,id:crypto.randomUUID(),title:active.title+' 副本'};setProject(p=>({...p,cards:[...p.cards,c]}));setSelected(c.id);}
 function remove(){if(!active)return;setUndo(project);setProject(p=>({...p,cards:p.cards.filter(c=>c.id!==selected)}));setSelected(project.cards.find(c=>c.id!==selected)?.id??'');setMessage('已移除卡片，可以撤销。');}
 function move(direction:number){const i=project.cards.findIndex(c=>c.id===selected),j=i+direction;if(i<0||j<0||j>=project.cards.length)return;const cards=[...project.cards];[cards[i],cards[j]]=[cards[j],cards[i]];setProject(p=>({...p,cards}));}
 function exportProject(){download(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),`${project.name||'环带项目'}.ring.json`);setMessage('项目已导出，包含全部参数和自定义图片。');}
 async function importProject(file?:File){if(!file)return;setBusy(true);try{if(file.size>24*1024*1024)throw new Error('项目文件需小于 24 MB。');const p=parseProject(JSON.parse(await file.text()));setUndo(project);setProject(p);setSelected(p.cards[0]?.id??'');setSeek(v=>v===0?.000001:0);setMessage('项目已载入。');}catch(e){setMessage(e instanceof Error?e.message:'无法读取该项目。');}finally{setBusy(false);if(importRef.current)importRef.current.value='';}}
 async function upload(file?:File){if(!file||!active)return;const id=active.id;setBusy(true);try{const image=await readImage(file);setProject(p=>({...p,cards:p.cards.map(c=>c.id===id?{...c,kind:'image',image}:c)}));setMessage('自定义页面已替换。');}catch(e){setMessage(e instanceof Error?e.message:'图片读取失败。');}finally{setBusy(false);if(imageRef.current)imageRef.current.value='';}}
 async function screenshot(){setBusy(true);try{if(!scene.current)throw new Error('画布尚未就绪。');download(await scene.current.capture(),`${project.name||'环带'}-画面.png`);setMessage('当前画面已导出。');}catch(e){setMessage(e instanceof Error?e.message:'图片导出失败。');}finally{setBusy(false);}}
 function preset(mode:string){const p=mode==='front'?{pitch:0,roll:0,yaw:0}:mode==='top'?{pitch:55,roll:0,yaw:0}:{pitch:defaults.pitch,roll:defaults.roll,yaw:0};setProject(v=>({...v,settings:{...v.settings,...p}}));}
 const slider=(key:keyof Omit<Settings,'background'|'lightColor'>,label:string,min:number,max:number,step=1,unit='')=><Slider key={key} label={label} value={settings[key]} min={min} max={max} step={step} unit={unit} onChange={v=>changeSetting(key,v)}/>;
 return <div className="app-shell">
  <header className="topbar"><div className="brand"><span className="brand-icon"><Orbit size={22}/></span><span>RING<span className="brand-thin"> STUDIO</span></span><span className="version">01</span></div><div className="project-title"><input aria-label="项目名称" maxLength={80} value={project.name} onChange={e=>setProject(p=>({...p,name:e.target.value}))}/><span className="save-status"><Check size={12}/>{saveState}</span></div><div className="top-actions"><Button onClick={()=>importRef.current?.click()} disabled={busy||!loaded}><FolderOpen size={15}/><span>打开项目</span></Button><Button onClick={screenshot} disabled={busy||!loaded||!project.cards.length}><ImageDown size={15}/><span>导出图片</span></Button><Button className="primary" onClick={exportProject} disabled={!loaded}><Download size={15}/><span>保存项目</span></Button></div></header>
  <input ref={importRef} type="file" accept=".json,.ring.json" hidden onChange={e=>void importProject(e.target.files?.[0])}/><input ref={imageRef} type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" hidden onChange={e=>void upload(e.target.files?.[0])}/>
  <main className="workspace">
   <aside className="library"><div className="panel-heading"><div><h1>卡片页面</h1><span className="count">{project.cards.length} / 16</span></div><Button className="icon-button" title="添加卡片" aria-label="添加卡片" onClick={add} disabled={project.cards.length>=16||!loaded}><Plus size={17}/></Button></div><p className="panel-hint">选择页面，编辑你的内容</p><div className="card-list" aria-label="卡片列表">{project.cards.map((card,i)=><button key={card.id} className={`card-row ${selected===card.id?'selected':''}`} aria-pressed={selected===card.id} onClick={()=>{setSelected(card.id);setTab('card');}}><Thumbnail card={card}/><span className="card-row-info"><span>{card.title||'未命名页面'}</span><small>{String(i+1).padStart(2,'0')} · {kindNames[card.kind]}</small></span></button>)}{!project.cards.length&&<div className="empty-list"><PanelsTopLeft size={26}/><p>还没有卡片</p><Button onClick={add}>添加第一张</Button></div>}</div><div className="library-foot"><span className="live-dot"/>每张卡片都能独立编辑</div></aside>
   <section className="stage-column" ref={studioRef}><div className="stage-heading"><div><span className="eyebrow">LIVE CANVAS</span><h2>让你的页面，转起来。</h2></div><div className="stage-tools"><span className="stage-count">{project.cards.length} 个曲面</span><Button className="icon-button" title="全屏预览" aria-label="全屏预览" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void studioRef.current?.requestFullscreen().catch(()=>setMessage('当前浏览器不支持全屏。'));}}><Maximize2 size={16}/></Button></div></div><div className="canvas-wrap"><Scene ref={scene} project={project} playing={playing&&loaded} time={seek} onTime={setDisplayTime} onDrag={onDrag}/><div className="canvas-top"><span><i/>实时三维预览</span><span>拖动画布调整视角</span></div>{!project.cards.length&&<div className="stage-empty"><Orbit size={32}/><h3>从一张卡片开始</h3><p>添加图表或上传你的页面，组成自己的环带。</p><Button className="primary" onClick={add}><Plus size={16}/>添加页面</Button></div>}<div className="canvas-bottom"><span>X {Math.round(settings.pitch)}° <b/> Y {Math.round(settings.yaw)}° <b/> Z {Math.round(settings.roll)}°</span><span>本地渲染 · 随改随看</span></div></div><div className="playback"><Button className="play-button" aria-label={playing?'暂停动画':'播放动画'} onClick={()=>setPlaying(v=>!v)} disabled={!project.cards.length}>{playing?<Pause size={17}/>:<Play size={17}/>}</Button><Button className="icon-button" aria-label="回到起点" title="回到起点" onClick={()=>setSeek(v=>v===0?.000001:0)}><RotateCcw size={16}/></Button><span className="time-readout">{displayTime.toFixed(1).padStart(4,'0')}<small> / 12.0 s</small></span><input aria-label="预览时间" className="scrubber" type="range" min={0} max={11.999} step={.01} value={displayTime} onChange={e=>{setPlaying(false);setSeek(Number(e.target.value));setDisplayTime(Number(e.target.value));}}/><span className="playback-label">{settings.speed===30?'一圈 / 12 秒':settings.speed===0?'环带静止':`一圈 / ${(360/Math.abs(settings.speed)).toFixed(1)} 秒`}</span></div><div className="stage-foot"><span>RING STUDIO — 一个轻量的环带动效工作台</span><span>图片与项目仅保存在本机</span></div></section>
   <aside className="inspector"><div className="inspector-tabs" role="tablist" aria-label="编辑面板">{([['scene','场景',SlidersHorizontal],['light','灯光',Sun],['card','页面',PanelsTopLeft]] as const).map(([value,label,Icon])=><button key={value} role="tab" aria-selected={tab===value} aria-controls={`panel-${value}`} id={`tab-${value}`} onClick={()=>setTab(value)}><Icon size={15}/>{label}</button>)}</div><div className="inspector-body" role="tabpanel" id={`panel-${tab}`} aria-labelledby={`tab-${tab}`}>
    {tab==='scene'&&<><section className="control-section"><div className="section-title"><h3>环带角度</h3><span>TRANSFORM</span></div><div className="preset-row"><Button onClick={()=>preset('default')}>经典斜视</Button><Button onClick={()=>preset('front')}>正视</Button><Button onClick={()=>preset('top')}>俯视</Button></div>{slider('pitch','俯仰 X',-80,80,1,'°')}{slider('yaw','朝向 Y',-180,180,1,'°')}{slider('roll','倾斜 Z',-180,180,1,'°')}</section><section className="control-section"><div className="section-title"><h3>形态与画面</h3><span>LAYOUT</span></div>{slider('radius','圆环半径',1.5,5,.05)}{slider('height','页面高度',.5,3.5,.05)}{slider('gap','页面间距',0,25,1,'%')}{slider('zoom','画面大小',40,150,1,'%')}<ColorField label="画布背景" value={settings.background} onChange={v=>changeSetting('background',v)}/>{slider('backOpacity','内侧可见度',0,1,.01)}</section><section className="control-section"><div className="section-title"><h3>动画节奏</h3><span>MOTION</span></div>{slider('speed','旋转速度',-90,90,1,'°/s')}{slider('chartSpeed','图表速度',.2,3,.1,'×')}<p className="help">负值反向旋转，0 停止环带。图表动画仍可独立播放。</p></section><Button className="wide subtle" onClick={()=>{setUndo(project);setProject(p=>({...p,settings:{...defaults}}));setSeek(v=>v===0?.000001:0);setMessage('场景参数已恢复，页面内容保留。');}}><RotateCcw size={14}/>恢复默认场景</Button></>}
    {tab==='light'&&<><section className="control-section"><div className="section-title"><h3>灯光预设</h3><span>LIGHTING</span></div><div className="light-presets">{[{name:'柔和日光',color:'#ffffff',power:2.2,ambient:1.7,angle:-35},{name:'暖色侧光',color:'#ffe0b8',power:3.5,ambient:.8,angle:-65},{name:'冷色轮廓',color:'#b9d7ff',power:4,ambient:.6,angle:130}].map(p=><button key={p.name} onClick={()=>setProject(v=>({...v,settings:{...v.settings,lightColor:p.color,lightPower:p.power,ambient:p.ambient,lightAngle:p.angle}}))}><span style={{background:p.color}}/><small>{p.name}</small></button>)}</div></section><section className="control-section"><div className="section-title"><h3>主光</h3><span>KEY LIGHT</span></div>{slider('lightAngle','水平方向',-180,180,1,'°')}{slider('lightElevation','灯光高度',-80,80,1,'°')}{slider('lightPower','主光强度',0,6,.1)}<ColorField label="灯光颜色" value={settings.lightColor} onChange={v=>changeSetting('lightColor',v)}/></section><section className="control-section"><div className="section-title"><h3>环境与材质</h3><span>SURFACE</span></div>{slider('ambient','环境亮度',0,4,.1)}{slider('roughness','表面粗糙度',.05,1,.01)}<p className="help">灯光跟随三维空间计算。降低环境亮度，可更清楚地看到侧面明暗。</p></section></>}
    {tab==='card'&&(active?<><section className="control-section"><div className="section-title"><h3>页面内容</h3><span>{String(project.cards.indexOf(active)+1).padStart(2,'0')}</span></div><Thumbnail card={active} large/><div className="card-actions"><Button aria-label="向前移动卡片" title="向前移动" onClick={()=>move(-1)} disabled={project.cards[0].id===active.id}><ChevronLeft size={15}/></Button><Button aria-label="向后移动卡片" title="向后移动" onClick={()=>move(1)} disabled={project.cards.at(-1)?.id===active.id}><ChevronRight size={15}/></Button><Button onClick={duplicate} disabled={project.cards.length>=16}><Copy size={14}/>复制</Button><Button className="danger" onClick={remove} title="删除卡片" aria-label="删除卡片"><Trash2 size={15}/></Button></div><label className="field"><span>页面类型</span><select value={active.kind} onChange={e=>{const k=e.target.value as CardKind;const c=newCard(k);patchCard({kind:k,values:c.values,title:c.title,value:c.value,color:c.color});}}>{kinds.map(k=><option key={k} value={k}>{kindNames[k]}</option>)}</select></label><Field label="标题" value={active.title} maxLength={80} onChange={e=>patchCard({title:e.target.value})}/>{active.kind!=='image'&&<><Field label="主数值 / 文案" value={active.value} maxLength={40} onChange={e=>patchCard({value:e.target.value})}/><ValuesField values={active.values} onChange={v=>patchCard({values:v})}/><ColorField label="主题颜色" value={active.color} onChange={v=>patchCard({color:v})}/></>}<ColorField label="卡片底色" value={active.background} onChange={v=>patchCard({background:v})}/>{active.kind!=='image'&&<label className="check-field"><span>图表动画</span><input type="checkbox" checked={active.animated} onChange={e=>patchCard({animated:e.target.checked})}/></label>}</section><section className="control-section"><div className="section-title"><h3>自定义页面</h3><span>YOUR DESIGN</span></div><button className="upload-box" onClick={()=>imageRef.current?.click()} disabled={busy}><Upload size={21}/><strong>{busy?'正在处理…':active.image?'替换页面图片':'上传自己的设计'}</strong><small>PNG、JPG、WebP、SVG · 最大 10 MB</small></button>{active.kind==='image'&&<label className="field"><span>图片适配</span><select value={active.fit} onChange={e=>patchCard({fit:e.target.value as Card['fit']})}><option value="contain">完整显示</option><option value="cover">铺满裁切</option></select></label>}<p className="help">上传 Figma 或 Illustrator 导出的页面图片，会自动贴合圆环曲面。</p></section></>:<div className="empty-list"><p>添加一张卡片开始编辑。</p><Button onClick={add}>添加页面</Button></div>)}
   </div></aside>
  </main>{message&&<div className="toast" role="status"><span>{message}</span>{undo&&<button onClick={()=>{setProject(undo);setSelected(undo.cards[0]?.id??'');setUndo(null);setMessage('已撤销。');}}>撤销</button>}<button aria-label="关闭提示" onClick={()=>setMessage('')}><X size={15}/></button></div>}
 </div>;
}
